version: '3'

services:
  app:
    build: .
    ports:
      - "6000:6000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/user-system-dev"
      PORT: 6000
      SECRETKEY: "Kcy_test"
    networks:
      - user-system-network
    depends_on:
      - mongo
    command: sh -c "npm run start"

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - user-system-network
    volumes:
      - mongo-data:/data/db

networks:
  user-system-network:

volumes:
  mongo-data:
